### ISSUE TITLE
Add the ability to pass in networks other than `mainnet, prater, pyrmont` - specially local testnets

### ISSUE THREAD

**Issue by h4ck3rk3y** [bloxapp/ssv#1025]
**Is your feature request related to a problem? Please describe.**
I am using the docker image `bloxstaking/ssv-node:latest` to create ssv nodes. It seems like for the configuration I can only pass in pyrmont,prater,mainnet` for the value `eth2.Network`. I am launching a custom test net and I want to pass that but the Golang code prevents me from doing so.

Seems like that has been recently changed to this list https://github.com/bloxapp/ssv/blob/ee0d75a872467d027eff791c565568db22fcb7dc/networkconfig/config.go#L15-L19 but it is still quite limiting

**Describe the solution you'd like**
The ability to pass in parameters for a self spun up test network

**Describe alternatives you've considered**
For now I am just passing `prater` 

**Additional context**
N/A

**Comment by lior-blox** [comment]
We added support for custom networks.
It can be found here
https://github.com/bloxapp/ssv/blob/main/networkconfig/NEW_NETWORK.md
