### ISSUE TITLE
configuration via environmental variables still requires yaml

### ISSUE THREAD

**Issue by tupakkatapa** [bloxapp/ssv#1138]
**Describe the bug**
Operator does not start even if the requires options are defined via environmental variables.

**To Reproduce**
```shell
~> export OPERATOR_KEY=$(cat /home/kari/ssv_operator_key)
~> export DB_PATH="/var/mnt/addons/ssv/db"
~> export LOG_LEVEL="info"
~> export NETWORK="mainnet"
~> export ETH_1_ADDR="ws://192.168.100.10:8545"
~> export BEACON_NODE_ADDR="http://192.168.100.10:5052"
~> export LOG_FILE_PATH="/var/mnt/addons/ssv/debug.log"
~> ssvnode start-node
2023/09/08 23:31:44 starting SSV node (version SSV-Node:latest)
2023/09/08 23:31:44 could not create loggercould not read config: open ./config/config.yaml: no such file or directory
```

**Expected behavior**
As there is an option to define the parameters of the operator via environmental variables (https://docs.ssv.network/run-a-node/operator-node/node-reference), the `ssvnode start-node` command should be able to start the node without the YAML configuration file if all the required options are defined.

**Node:**
 - Operator Version: v1.0.0-rc.1 (latest)

**Comment by moshe-blox** [comment]
Hey, thanks for reporting, I think it's very reasonable for the node to run without a `config.yaml`. We're added this task to our backlog.

In the meantime, you can try this command to run the node "without" an `config.yaml`:
```bash
touch config/config.yaml && ssvnode start-node
```
