### ISSUE TITLE
Feature: Support for fallback execution / consensus clients

### ISSUE THREAD

**Issue by yorickdowne** [bloxapp/ssv#114]
It'd be useful to be able to specify comma-separated values for consensus ("beacon") and execution ("eth1") clients:

```
BeaconNodeAddr: consensus-1.example.com:443,consensus-2.example.com:443
ETH1Addr: wss://execution-1.example.com,wss://execution-2.example.com
```

That way, maintenance on a consensus or execution client - software and OS updates - do not impact the node.

Current solutions, without this feature, would include a ws(s) proxy such as the Fiews proxy; and for the consensus client, a https proxy would work once LH/Teku are supported. However, having this support natively without the need for proxy sidecars would be neat.

**Comment by mgarciate** [comment]
Yep, I'd like this feature
