### ISSUE TITLE
File log `debug.log` can configure log level or close

### ISSUE THREAD

**Issue by duktig666** [bloxapp/ssv#1155]
**Is your feature request related to a problem? Please describe.**
During operation, the SSV operator generates a large number of debug logs and writes them to files, occupying a large amount of disk space.

**Describe the solution you'd like**
File logs can be configured with log levels or turned off.

**Describe alternatives you've considered**

**Additional context**

See ssv code below:

**The console log can be configured at the log level, but the file log code is directly defined as debug and cannot be configured or turned off.**

https://github.com/bloxapp/ssv/blob/2fed2d63f40689014ff10df5aa2e57897f0dae68/logging/global.go#L75-L90

**Comment by y0sher** [comment]
log file configurations have been introduced in https://github.com/bloxapp/ssv/pull/1129
