### ISSUE TITLE
when ssv SyncOngoing meet the limit exceeded error, it may cause ssv process exit

### ISSUE THREAD

**Issue by hwhe** [bloxapp/ssv#1256]
**Describe the bug**

my ssv node started, the eventSyncer goroutine will loop to sync current block from beacon node. 
```
		// Sync ongoing registry events in the background.
		go func() {
			err = eventSyncer.SyncOngoing(ctx, fromBlock.Uint64())

			// Crash if ongoing sync has stopped, regardless of the reason.
			logger.Fatal("failed syncing ongoing registry events",
				zap.Uint64("last_processed_block", lastProcessedBlock),
				zap.Error(err))
		}()
```

in the SyncOngoing function, it has a loop to get logs, 

```
for {
			select {
			case <-ctx.Done():
				return
			case <-ec.closed:
				return
			default:
				lastBlock, err := ec.streamLogsToChan(ctx, logs, fromBlock)
				if errors.Is(err, ErrClosed) || errors.Is(err, context.Canceled) {
					// Closed gracefully.
					return
				}

				// streamLogsToChan should never return without an error,
				// so we treat a nil error as a an error by itself.
				if err == nil {
					err = errors.New("streamLogsToChan halted without an error")
				}

				tries++
				if tries > 2 {
					ec.logger.Fatal("failed to stream registry events", zap.Error(err))
				}
				if lastBlock > fromBlock {
					// Successfully streamed some logs, reset tries.
					tries = 0
				}

				ec.logger.Error("failed to stream registry events, reconnecting", zap.Error(err))
				ec.reconnect(ctx)
				fromBlock = lastBlock + 1
			}
		}

```
the streamLogsToChan use a websocket protocal  and eth_getLogs function to fetch block log from beacon node。my beacon node is a node shared by multy validator client and has a low API limit per second. now it occur a websocket limit exceeded error and  cant got the lastBlock value from the block , so the lastBlock  use the defalt value 0. and set fommBlock to 1.  it will cause reconnect from block 1 in a loop.
**To Reproduce**

**Expected behavior**
if meet the limit execceed error, the lastBlock may be 0, i think it should reconnet form the fromBlock not the 1.

**Screenshots**

**Node (please complete the following information):**
 - Operator Version: v1.2.1
 - BN Client  Lighthouse

**Additional context**

**Comment by y0sher** [comment]
It's a requirement that you'll have a functioning and responding in reasonable time execution and beacon nodes. we are syncing events from the execution node (usually geth) so the case you are describing isn't related to the beacon node. 
When the nodes fail to respond our we fail to keep track of the changes, the SSV node crashes to prevent working with outdated data and the risk of slashing.
For further investigation of your exact situation, please provide more information about the setup you are running (ssv and eth nodes setup, machines, etc), and debug logs where this is happening (found in `./data/debug.log`).
closing this for now and you are welcome to create a new more detailed issue.
