### ISSUE TITLE
Failed to get v3 proposal after upgrading to 1.3.0

### ISSUE THREAD

**Issue by lilkk-jerry** [bloxapp/ssv#1333]
**Describe the bug**
With SSV Operator v1.3.0 connecting to Prysm 5.0.0, all of the proposal task will failed. Here is the log:

> **{"L":"DEBUG","T":"2024-03-04T05:57:24.220Z","N":"Controller.Validator","M":"❗ could not handle message","pubkey":"94265b7b9e7fca927ab50e9e77382c7a2f08ecaa03f3d2a47c2b36c93f1a2a55e7005757020aeab2aa20166c41f3175e","role":"PROPOSER","signer"        :70,"slot":8558985,"msg_type":"partial_signature","error":"failed to get blinded beacon block: failed to get v3 proposal: missing Eth-Execution-Payload-Blinded header"**

We've already finished the troubleshoot, this is because a line of code is missed in github.com/y0sher/go-eth2-client.git, v3proposal.go/v3ProposalFromJson:

![image](https://github.com/bloxapp/ssv/assets/82644847/92117105-4373-4489-b120-8054be4b47bf)

**To Reproduce**
1. Connect SSV Operator to Prysm 5.0.0
2. Wait for a proposal task, and it would fail

**Node**
 - Operator Version: 1.3.0
 - BN Client: Prysm 5.0.0

**Comment by y0sher** [comment]
@lilkk-jerry, thanks for filling this bug report. it seems like you are correct and this is indeed a missing line there that causing your issues. we have tested with several different clients but it seems like our tests skipped clients that return JSON content type. I don't understand why your Prysm node responses with JSON though as we are not requesting it from SSV itself.

Anyway a fix is on the way.

**Comment by lilkk-jerry** [comment]
> @lilkk-jerry, thanks for filling this bug report. it seems like you are correct and this is indeed a missing line there that causing your issues. we have tested with several different clients but it seems like our tests skipped clients that return JSON content type. I don't understand why your Prysm node responses with JSON though as we are not requesting it from SSV itself.
> 
> Anyway a fix is on the way.

@y0sher Hi, yes we provide a proxy to optimize the QoS, and it will change the Content-Type. I wonder when the fix would be officially released? If after Mainnet Dencun, we will consider make some change in our proxy.

**Comment by y0sher** [comment]
Fix merged, released in 1.3.1.
