### ISSUE TITLE
Re-think networking implementation

### ISSUE THREAD

**Issue by amir-blox** [bloxapp/ssv#186]

**Comment by alonmuroch** [comment]
@amir-blox some points I had when I thought of it:
1) support for different networking
2) divide to different protocols which a node can decide to adopt or not
3) ping/ point msgs that describe the node, what protocols it supports, version and so on
4) standardize tx encoding
5) documentation!
6) separate to a different project? I saw ethereum did that so if someone wants to run just the networking he can

as a reference: https://github.com/ethereum/devp2p/blob/master/caps/eth.md
