### ISSUE TITLE
Implement Proposal logic [COPIED]

### ISSUE THREAD

**Issue by AmitaiBlox** [bloxapp/ssv#24]

**Comment by lior-blox** [comment]
Was done by @roman-blox

**Comment by lior-blox** [comment]
reopened
https://pyrmont.beaconcha.in/validator/b4dbeb61df8d810ff7c3d319716c867ac8d717ac6037413e66f543ec031fd23f10d58cf0f94831ec4963b9dc6d6555ad#blocks

**Comment by lior-blox** [comment]
Will be done as part of spec alignment
