### ISSUE TITLE
Pre-prepare message pipeline error (unjustified)

### ISSUE THREAD

**Issue by amir-blox** [bloxapp/ssv#265]
There are errors in pre-prepare message pipeline:
`msg pipeline error {"error": "Unjustified pre-prepare: no change round quorum"}`

https://github.com/bloxapp/ssv/blob/64b938fc15b5d3d3573d9180bf17ffdde114092d/ibft/pre_prepare.go#L49

**Comment by alonmuroch** [comment]
@amir-blox Is this an issue?

**Comment by nivBlox** [comment]
@alonmuroch the error itself is not an issue - still investigate if the cause is ok or not
