### ISSUE TITLE
IP address is not accessible whereas port is opened

### ISSUE THREAD

**Issue by pablomendezroyo** [bloxapp/ssv#289]
Hi there!

I am Pablo from DAppNode team, we have developed a DAppNodePackage for SSV: https://github.com/dappnode/DAppNodePackage-SSV

I am getting the following error while starting up the container on a remote linux server:
```
2p/p2p.go:178    IP address is not accessible    {"app": "SSV-Node:v0.0.16", "component": "p2p", "id": "16Uiu2HAmJV4oiFA7mRu8y8ZzKyAQuJVp9aBsJAw47oexDXxFqjVP", "error": "dial tcp X.X.X.X:13000: i/o timeout"}
```
which in SSV source code is https://github.com/bloxapp/ssv/blob/d641686a5d46d088d1f6cd4b48c8396e88bd261d/network/p2p/p2p.go#L176 

I have double-checked that the host port **13000** is opened and properly mapped to the SSV container port **13000**

Also, I have set up on a local machine the SSV and it works fine whereas on a remote it fails with the above error.

Do you have an idea whats going one? might be some any networking traffic blocker?

**Comment by pablomendezroyo** [comment]
## UPDATE
I was able to make SSV working by doing `ufw disable` on my host machine. The ufw was blocking the check you have for the `<publicIP>:13000`. The check should be edited so be edited so users do not have to edit host machine settings, or even been deleted

**Comment by yorickdowne** [comment]
0.1.4 fixed a similar issue for me, it now listens on 0.0.0.0 for 13000/tcp. I can now "host map" the port and don't have to go through an ingress.
