### ISSUE TITLE
Grafana node dash hardcodes FQDN for validator dash

### ISSUE THREAD

**Issue by yorickdowne** [bloxapp/ssv#323]
Line 426: `                    "url": "https://grafana.k8s.blox.io/d/${validator_dashboard_id}/ssv-validator?orgId=1&refresh=10s&var-instance=${instance}&var-pubkey=${__data.fields[\"Public Key\"]}"`

This link should use a variable for the FQDN.

**Comment by amir-blox** [comment]
I've removed the host in https://github.com/bloxapp/ssv/commit/4228bc4bb0f269d3457d4b6293e6e9b9eb1aa86e, so the browser will use the current domain.

Do you think there are cases that the validator dashboard will reside in another domain?

**Comment by yorickdowne** [comment]
I think that's highly unlikely. I expect them to be on the same domain, since the data come from the same node.
