### ISSUE TITLE
Grafana dashboards are not available sometimes

### ISSUE THREAD

**Issue by amir-blox** [bloxapp/ssv#329]
Could be the size (and the derived latency) of metrics response.

In `ssv-exporter`:
```
curl http://localhost:15000/metrics > 1609_metrics.out
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  235M    0  235M    0     0  9257k      0 --:--:--  0:00:26 --:--:-- 34.4M
```

`ssv-node-1`:
```
bash-5.0# curl http://localhost:15000/metrics > 2809_metrics.out
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  183M    0  183M    0     0  6326k      0 --:--:--  0:00:29 --:--:-- 24.5M
```

**Comment by mgarciate** [comment]
Yep, my operator returns 140 MB of metrics spending around 15 seconds on every request to /metrics, which makes very difficult (impossible at this time) to monitoring

**Comment by amir-blox** [comment]
`ssv:network:ibft_messages_inbound` is a problematic metric which grows infinitely over time.

The metric have labels for `round` and `sequence` which grows in time until the response becomes too large as specified above.

e.g. 
`ssv:network:ibft_messages_inbound{pubKey="80f8f...",round="1",seq="4040",signer="3",type="Prepare"} 1`
`ssv:network:ibft_messages_inbound{pubKey="80f8f...",round="2",seq="4040",signer="3",type="Prepare"} 1`
`ssv:network:ibft_messages_inbound{pubKey="80f8f...",round="1",seq="4041",signer="3",type="Prepare"} 1`
...
