### ISSUE TITLE
Exporter README mistake

### ISSUE THREAD

**Issue by nivBlox** [bloxapp/ssv#418]
**Describe the bug**
https://github.com/bloxapp/ssv/tree/main/exporter#data-sources
"Slot (slot: uint64) --> part of the lambda" is incorrect. slot is not part of the lambda

**Comment by amir-blox** [comment]
Fixed in https://github.com/bloxapp/ssv/commit/f86fc9f11c3c2d0eb2375165742ed2312c5315d8
