### ISSUE TITLE
Leak in message pipeline

### ISSUE THREAD

**Issue by amir-blox** [bloxapp/ssv#434]
**Describe the bug**

`Instance.StartMessagePipeline` (`./ibft/instance/event_loop.go`) is causing leaks when the function was not executed and therefore the WaitGroup remains locked, usually happens when the queue is stopped while there are items in it:
https://github.com/bloxapp/ssv/blob/4b1ae493621246e434e2550730c89dbea625c70c/ibft/instance/event_loop.go#L65

**To Reproduce**

**Expected behavior**

**Screenshots**

**Node (please complete the following information):**
 - Operator Version: `v0.1.4`

**Additional context**

**Comment by nkryuchkov** [comment]
Should be resolved by https://github.com/bloxapp/ssv/pull/435
