### ISSUE TITLE
Grafana - wrong IBFT status IDLE instead of ERROR

### ISSUE THREAD

**Issue by amir-blox** [bloxapp/ssv#437]
**Describe the bug**

IBFT status will always get back to `IDLE` even if it should be `ERROR`, and because of https://github.com/bloxapp/ssv/issues/436 should remain on `ERROR`.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Node (please complete the following information):**
 - Operator Version: v0.1.4

**Additional context**

**Comment by nkryuchkov** [comment]
Should be fixed by #438
