### ISSUE TITLE
Alpine DNS Resolving

### ISSUE THREAD

**Issue by nivBlox** [bloxapp/ssv#450]
**Describe the bug**
DNS resolving on Alpine is not working. Currently there is a separate image for with ubuntu OS.
Need to find how to work with alpine. 

**To Reproduce**
1. setup ssv with eth nodes on same machine with docker
2. set the BN/ETH1 end point with network 
3. ssv node cant connect to node

**Comment by BarnumD** [comment]
Experienced this in kubernetes cluster, which fails to resolve service names via DNS.
