### ISSUE TITLE
 Unable to create external multiaddress

### ISSUE THREAD

**Issue by tangtang666** [bloxapp/ssv#503]
**Describe the bug**

docker run -d --restart unless-stopped --name=ssv_node -e \
CONFIG_PATH=./config.yaml -p 13000:13000 -p 12000:12000 -v \
$SSV_DB/config.yaml:/config.yaml -v $SSV_DB:/data -it \
'bloxstaking/ssv-node:latest' make BUILD_PATH=/go/bin/ssvnode start-node

Unable to create external multiaddress  {"app": "SSV-Node:v0.1.9", "component": "p2p", "id": "16Uiu2HAmDkEWVKuPViXzWSwwasvV6m7UoHcrvMEDgfB42sSnTv97", "error": "invalid ip address provided:  ; <<>> DiG 9.16.20 <<>> @resolver4.opendns.com myip.opendns.com +short ; (1 server found) ;; global options: +cmd ;; connection timed out; no servers could be reached", "errorVerbose": "invalid ip address provided:  ; <<>> DiG 9.16.20 <<>> @resolver4.opendns.com myip.opendns.com +short ; (1 server found) ;; global options: +cmd ;; connection timed out; no servers could be reached\ngithub.com/bloxapp/ssv/network/p2p.buildMultiAddress\n\t/go/src/github.com/bloxapp/ssv/network/p2p/addr_utils.go:140\ngithub.com/bloxapp/ssv/network/p2p.(*p2pNetwork).configureAddrs.func1\n\t/go/src/github.com/bloxapp/ssv/network/p2p/options.go:100\ngithub.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).Addrs\n\t/go/pkg/mod/github.com/libp2p/go-libp2p@v0.15.1/p2p/host/basic/basic_host.go:752\ngithub.com/libp2p/go-libp2p/p2p/protocol/identify.(*IDService).getSnapshot\n\t/go/pkg/mod/github.com/libp2p/go-libp2p@v0.15.1/p2p/protocol/identify/id.go:465\ngithub.com/libp2p/go-libp2p/p2p/protocol/identify.newPeerHandler\n\t/go/pkg/mod/github.com/libp2p/go-libp2p@v0.15.1/p2p/protocol/identify/peer_loop.go:48\ngithub.com/libp2p/go-libp2p/p2p/protocol/identify.(*IDService).loop\n\t/go/pkg/mod/github.com/libp2p/go-libp2p@v0.15.1/p2p/protocol/identify/id.go:212\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"}

**Comment by yorickdowne** [comment]
" connection timed out; no servers could be reached" - that's not a bug in SSV, that means the system you ran this on couldn't reach opendns.com.
