### ISSUE TITLE
Consider using `sync/atomic` instead of `utils/threadsafe`

### ISSUE THREAD

**Issue by nkryuchkov** [bloxapp/ssv#552]
**Is your feature request related to a problem? Please describe.**
Most `utils/threadsafe`'s types can be replaced by more efficient `sync/atomic`. Also, `utils/threadsafe` can be `nil` and cause panic if it's not checked. Probably it causes https://github.com/bloxapp/ssv/issues/538

**Describe the solution you'd like**
Replace `utils/threadsafe` with `sync/atomic` where it's possible

**Describe alternatives you've considered**
Leave it as it is and check if `nil`-values are checked everywhere

**Additional context**
The issue doesn't seem urgent

**Comment by ef3n9r98** [comment]
Hi @nkryuchkov, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by nkryuchkov** [comment]
Hi @ef3n9r98,

Thank you for the suggestion, but this issue is outdated.

/cc @lior-blox
