### ISSUE TITLE
[Investigation] Fee replacement attack

### ISSUE THREAD

**Issue by alonmuroch** [bloxapp/ssv#573]
**Describe the bug**
SSV smart contracts give fee according to operator ID but there is nothing in the contract that checks the encrypted shares belong to that operator ID.
If we do not check in the node while parsing events that the reported operator ids match the encrypted shares then someone can report operator ids 1,2,3,4 but submit shares belonging to operators 5,6,7,8 which will result in operators 5-8 working for "free"

We need to make sure the node checks that.

**Comment by olegshmuelov** [comment]
By parsing ETH1 events, we verify where the event belongs to the operator attempting to decipher the share secret key (the encrypted key). If the decryption fails, we simply skip the event and don't keep handling it.
In this way, "false" operator identifiers will not be treated with the appropriate operator nodes.

**Comment by lior-blox** [comment]
@olegshmuelov lets add a test case for it

**Comment by y0sher** [comment]
this seems to be done.
