### ISSUE TITLE
Correction to IBFT.md

### ISSUE THREAD

**Issue by AmitaiBlox** [bloxapp/ssv#62]
It is implied in this doc that IBFT is relevant only to block proposals, when in fact it's also relevant to attestations. Please correct this so it'll be clearer that IBFT is for both duty types. 

https://github.com/bloxapp/ssv/blob/stage/ibft/IBFT.md

**Comment by vinipx** [comment]
@AmitaiBlox thanks for reviewing it. Could you please elaborate where to fix? 

Here you can find the section where both are mentioned:

_...operating on an Ethereum network - ETH 2.0 - for **Attestation and Proposal.**_

**Comment by AmitaiBlox** [comment]
@vinipx look under "Terminology" and "Consensus States"
