### ISSUE TITLE
How does your DKG work?

### ISSUE THREAD

**Issue by zicofish** [bloxapp/ssv#667]
Hi, how does DKG work in your system? Any paper reference?

Specifically, I think Eth2 requires validation key and withdrawal key to be generated from a mnemonic, which is discussed [here](https://blog.ethereum.org/2020/05/21/keys/). 

I was wondering whether your DKG is compatible with this process?

**Comment by yorickdowne** [comment]
SSV uses the keystore JSON file generated by staking-deposit-cli, and then distributes it. That means users are free to always remove their key again and use it elsewhere; and of course they have full use of their mnemonic, can set an `--eth1_withdrawal_address`, etc.

**Comment by y0sher** [comment]
we now support full DKG by running a separate DKG operator node that shares your operator private key. you can run it on same machine or different machine.  **NOTE: its in audit process so I wouldn't use in mainnet until its done.**
https://github.com/bloxapp/ssv-dkg
