### ISSUE TITLE
Ibft sync timeout

### ISSUE THREAD

**Issue by amir-blox** [bloxapp/ssv#75]
In case share dont have any peers it stuck in infinate loop to wait for peers.
need to add some timeout to stop

**Comment by nivBlox** [comment]
@alonmuroch @lior-blox what do think?

**Comment by lior-blox** [comment]
@amir-blox @nivBlox 
I think our current implementation to wait until min peers with resetting timeout logic solve that problem.
i think we can close

**Comment by nivBlox** [comment]
agree, closing
