### ISSUE TITLE
Load current instance when booting

### ISSUE THREAD

**Issue by amir-blox** [bloxapp/ssv#76]
Current instance state is saved into storage when it hits a prepare quorum. The idea is to save it in case the node crashes right after so when he boots again he can load the prepare state and continue from there.

**Comment by nivBlox** [comment]
IMO we shouldn't load state. ibft should start from zero when boot in order to not miss some ibft decisions also, it can cause sync issues 

@alonmuroch any thought? also what is the reason in the first place to save the state? except from metric (collector) there is no use of it

**Comment by alonmuroch** [comment]
The only thing I can think of is what happens if during an instance the node crashes. 
It won't start another instance for another epoch which will halt consensus.

**Comment by nivBlox** [comment]
After discussions, decided to wait with that issue for future develop
