### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by amir-blox** [bloxapp/ssv#85]
The following places in code needs more tests:
1. node/node.go - unit tests can be added, need to decouple code by breaking node.go::Start
2. slotqueue - add unit tests
3. Tests are commented out - need to remove or uncomment:
    - `ibft/spectesting/algorithm_test.go` 
    - `utils/threshold/threshold_test.go`

**Comment by nivBlox** [comment]
@lior-blox can we remove `utils/threshold/threshold_test.go` commented tests?
