### ISSUE TITLE
Refactor InstanceParams/ ValdiatorShare and Me variables

### ISSUE THREAD

**Issue by amirylm** [bloxapp/ssv#89]
All of the above are basically the same thing. 
The functionality we are looking for is:
1) pass consensus params to iBFT and then Instance
2) pass share and committee info to iBFT and instance 

We should refactor to have a single standardized way to pass and use this info

@nivBlox @lior-blox

**Comment by alonmuroch** [comment]
@amir-blox I think this is done, if so we can close
